apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: us.gcr.io/ticketz-dev/auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: ticketz-dev
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
